### PR TITLE
[DEV] Make a Unit test framework

### LINKED ISSUE #18: Create test framework  based on node.js to test story (SUCCESS and more) later

### PR DESCRIPTION
**Pull request by miong**
fix #18

### CODE REVIEW

**Comment by miong** [comment]
No need to analyse node_module directory ;)

**Comment by miong** [comment]
@Mergifyio rebase

**Review by law0 — DISMISSED** [review]
Error encountered : 
✔ ~/Workspace/tests/MakeYourChoices [:aae9689|✚ 1…6] 
14:22 $ ./test.sh
Running Unit tests
--- Test Main ---
Add test file declaration : libtest_ut
Add test file declaration : story_ut

Start tests execution from 2 files

--------------------
Executing libtest_ut
--------------------
/home/law/Workspace/tests/MakeYourChoices/test/libtest.js:83
		assertStrict.ok(currentModules.has(moduleName), "Module "+moduleName+" have not been declared yet.");
		             ^

TypeError: Cannot read property 'ok' of undefined
    at Object.declare_test (/home/law/Workspace/tests/MakeYourChoices/test/libtest.js:83:16)
    at Object.module.exports.testRunnable (/home/law/Workspace/tests/MakeYourChoices/test/libtest_ut.js:6:9)
    at /home/law/Workspace/tests/MakeYourChoices/test/libtest.js:129:11
    at Array.forEach (<anonymous>)
    at Object.execute_tests (/home/law/Workspace/tests/MakeYourChoices/test/libtest.js:120:13)
    at Object.<anonymous> (/home/law/Workspace/tests/MakeYourChoices/test/main.js:10:9)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)

**Review by law0 — APPROVED** [review]
Tested on another computer. Debian. Worked.

**Pull request merged**
